baseURL = "https://ignutanz.github.io/"
languageCode = "en-us"
title = "Tanzeem alias iGNUjee's Tech minutes"
theme = "geekblog"

# Required to get well formatted code blocks
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true
